### ISSUE TITLE
Running the contributed command:'vim.h' failed.

### ISSUE THREAD

**Issue by wulei** [74th/vscode-vim#7]
Hi, tks for you plugin,but ...
workbench.main.js:1602 [Plugin Host] Cannot read property 'length' of undefined
workbench.main.js:1602 [Plugin Host] Object {}

**Comment by wulei** [comment]
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/applicationinsights/Librar…:19 ApplicationInsights:Sender 
[Error: read ETIMEDOUT at exports._errnoException (util.js:837:11) at TLSWrap.onread (net.js:…]
0: Error: read ETIMEDOUT at exports._errnoException (util.js:837:11) at TLSWrap.onread (net.js:544:26)
length: 1
__proto__: Array[0]

**Comment by wulei** [comment]
maybe add vim state in bottom bar??

**Comment by benjaminRomano** [comment]
@wulei 
Vim Mode has been added to the bottom bar.
see https://github.com/74th/vscode-vim/issues/13 for details on how to enable it.

**Comment by 74th** [comment]
I cannot found this error. But I fixed some bugs.
Please reinstall this plugins and try it.

**Comment by msherwood21** [comment]
Just installed thirty minutes ago and can confirm this issue is still present.

**Comment by msherwood21** [comment]
To help you better track down this issue, here are the steps to reproduce the error:
1. Open a new document or open a document and place the cursor on a blank line
2. Enter insert mode through either 'i' or 'a'
3. Type Shift+H

**Comment by 74th** [comment]
Please update this plugin.

**Comment by msherwood21** [comment]
I have updated and can confirm it's working correctly now.
